# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  branch = "master"
  name = "github.com/asaskevich/EventBus"

[[constraint]]
  branch = "master"
  name = "github.com/dimiro1/health"

[[constraint]]
  name = "github.com/fatih/structs"
  version = "1.0.0"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  name = "github.com/go-errors/errors"
  version = "1.0.1"

[[constraint]]
  name = "github.com/go-playground/locales"
  version = "0.12.1"

[[constraint]]
  name = "github.com/go-playground/universal-translator"
  version = "0.16.0"

[[constraint]]
  name = "github.com/go-stack/stack"
  version = "1.7.0"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.1.1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.6"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "github.com/wheniwork/n1ql-query-builder"
  version = "0.3.3"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.9.0"

[[constraint]]
  name = "gopkg.in/couchbase/gocb.v1"
  version = "1.4.0"

[[constraint]]
  name = "gopkg.in/couchbase/gocbcore.v7"
  version = "7.1.3"

[[constraint]]
  name = "gopkg.in/go-playground/validator.v9"
  version = "9.20.2"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/gavv/httpexpect.v1"

[prune]
  go-tests = true
  unused-packages = true
